### PR TITLE
Include "id" resource properties as "awsId"

### LINKED ISSUE #1036: Missing required field on MediaPackage OriginEndpointArgs
### What happened?

I try to create a simple OriginEndpoint and I fillout out every required attribute as far as your interface suggests https://github.com/pulumi/pulumi-aws-native/blob/360bc11ff2538e17bacfb34c512cd1b34ef7ba50/sdk/nodejs/mediapackage/originEndpoint.ts#L140

with code like ...
```
const originEndpoint = new OriginEndpoint(`my-test-origin-endpoint`,
    {
        channelId: channelId,
        hlsPackage: {
            adMarkers: OriginEndpointHlsPackageAdMarkers.None,
            adTriggers: [
                OriginEndpointHlsPackageAdTriggersItem.SpliceInsert,
                OriginEndpointHlsPackageAdTriggersItem.ProviderAdvertisement,
                OriginEndpointHlsPackageAdTriggersItem.DistributorAdvertisement,
                OriginEndpointHlsPackageAdTriggersItem.ProviderPlacementOpportunity,
                OriginEndpointHlsPackageAdTriggersItem.DistributorPlacementOpportunity
            ],
            adsOnDeliveryRestrictions: OriginEndpointAdsOnDeliveryRestrictions.Restricted,
            includeDvbSubtitles: false,
            includeIframeOnlyStream: false,
            playlistType: OriginEndpointHlsPackagePlaylistType.Event,
            playlistWindowSeconds: 60,
            programDateTimeIntervalSeconds: 0,
            segmentDurationSeconds: 6,
            streamSelection: {
                maxVideoBitsPerSecond: 2147483647,
                minVideoBitsPerSecond: 0,
                streamOrder: OriginEndpointStreamSelectionStreamOrder.VideoBitrateAscending
            },
            useAudioRenditionGroup: false
        },
        manifestName: "index",
        origination: OriginEndpointOrigination.Allow,
        startoverWindowSeconds: 0,
        timeDelaySeconds: 0
    })
```

I try and pulumi up and I get...
```
 aws-native:mediapackage:OriginEndpoint (my-test-origin-endpoint):
    error: creating resource: operation error CloudControl: CreateResource, https response error StatusCode: 400, RequestID: e6dcdea0-c74e-468b-a924-bcf6
7ed0c856, api error ValidationException: Model validation failed (#: #: only 1 subschema matches out of 2
    #: required key [Id] not found)
```

### Expected Behavior

As per the AWS official documentation 
https://docs.aws.amazon.com/cli/latest/reference/mediapackage/create-origin-endpoint.html

I should be able to supply an id string and get a successful creation of an origin endpoint

### Steps to reproduce

I mentioned this in the description

### Output of `pulumi about`

```
Dependencies:
NAME                VERSION
@pulumi/aws-native  0.73.0
@pulumi/aws         5.42.0
@pulumi/awsx        1.0.4
@pulumi/pulumi      3.78.1
@types/node         16.18.40

```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by danielrbradley**
Fixes #1036 

- Rename to `awsId` to avoid clashing with Pulumi's own `id`.
- Don't change properties called "id" in sub-types as these are allowed.
- Extend irreversible names check to cover anything that doesn't round-trip (including our manual "awsId" change).
- Move checks for required and read-only properties to within the property loop.

### CODE REVIEW

File: provider/pkg/schema/gen.go [hunk 1]
```diff
@@ -847,37 +849,26 @@ func (ctx *context) gatherResourceType() error {
 		}
 		addUntypedPropDocs(propertySpec, ctx.cfTypeName)
 		properties[sdkName] = *propertySpec
-		if createOnlyProperties.Has(sdkName) || !readOnlyProperties.Has(prop) {
+		if requiredProperties.Has(prop) || readOnlyProperties.Has(prop) {
+			required.Add(sdkName)
```
Comment (thomas11) [inline provider/pkg/schema/gen.go:853]: Read-only properties are required? I don't understand that part.

**Review by thomas11 — APPROVED** [review]
LGTM modulo one question

File: provider/pkg/schema/gen.go (hunk 1 above)
Comment (danielrbradley) [reply provider/pkg/schema/gen.go:853]: Yeah, I'm not 100% sure on the reason for this logic - that read-only properties are guarenteed to be present as outputs. This just maintains the current behaviour which was previously written as:
```go
	for prop := range readOnlyProperties {
		sdkName := ToSdkName(prop)
		if _, has := properties[sdkName]; has {
			required.Add(sdkName)
		}
	}
```
