### PR TITLE
Handle AlreadyExists error during creation

### LINKED ISSUE #1138: KMS alias does not interpret AWS Cloud Control error correctly, removing other alias!
### What happened?

If you try to create a KMS alias that already exists (accidentally) you get back an error. However, pulumi seems to register that the alias was successful. So when you try to change the alias name and run pulumi again (to create a non-existing alias), pulumi will see this as a replace command, deleting the existing KMS alias that is being used by another KMS key (this is no fun with production data....).

### Example

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws-native";
import * as awsClassic from "@pulumi/aws";

const { partition } = await aws.getPartition();
const { accountId } = await aws.getAccountId();

const key1 = new aws.kms.Key("kms-encrypt-key", {
    name: "testing",
    description: "Testing",
    enabled: true,
    keySpec: "SYMMETRIC_DEFAULT",
    multiRegion: false, // On update set this to true
    pendingWindowInDays: 7,
    keyPolicy: awsClassic.iam.getPolicyDocumentOutput({
        statements: [
            {
                sid: "Enable all User Permissions for root account",
                actions: ["kms:*"],
                resources: ["*"],
                effect: "Allow",
                principals: [{
                    type: "AWS",
                    identifiers: [`arn:${partition}:iam::${accountId}:root`],
                }]
            }
        ],
    }).json,
});

const key2 = new aws.kms.Key("kms-encrypt-key-2", {
    name: "testing",
    description: "Testing",
    enabled: true,
    keySpec: "SYMMETRIC_DEFAULT",
    multiRegion: false, // On update set this to true
    pendingWindowInDays: 7,
    keyPolicy: awsClassic.iam.getPolicyDocumentOutput({
        statements: [
            {
                sid: "Enable all User Permissions for root account",
                actions: ["kms:*"],
                resources: ["*"],
                effect: "Allow",
                principals: [{
                    type: "AWS",
                    identifiers: [`arn:${partition}:iam::${accountId}:root`],
                }]
            }
        ],
    }).json,
});

new aws.kms.Alias("kms-alias-1", {
    aliasName: `alias/testing/1`,
    targetKeyId: key1.arn
});
```

1. Up the pulumi program above.
2. Add a second alias:

```
new aws.kms.Alias("kms-alias-2", {
    aliasName: `alias/testing/1`, // On purpose this is the same alias as alias 1.
    targetKeyId: key2.arn
});
```

3. Up pulumi again, you get an error:

```
  aws-native:kms:Alias (kms-alias-2):
    error: 1 error occurred:
        * operation CREATE failed with "AlreadyExists": An alias with the name arn:aws:kms:REGION:XXXX:alias/testing/1 already exists (Service: Kms, Status Code: 400, Request ID: XXXX)
```

4. Change the `aliasName` of `kms-alias-2` into `aliasName: "alias/testing/2"`.
5. Notice that the alias of key1 is being deleted (because of a replace action of kms-alias-2), which must NOT be the case. Instead it should have been a CREATE action.

### Output of `pulumi about`

```
NAME                VERSION
@pulumi/aws         6.50.0
@pulumi/aws-native  0.81.0
@pulumi/pulumi      3.89.0
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #1263: Dynamodb: on failure (duplicate name) pulumi throws away existing database
### What happened?

When creating a second DynamoDB table, I forgot to change the name of the second table to any other name that the first table (copy and paste lines of code without changing name). Pulumi brought back the AWS error that a table already existed with the same name. I changed the name of the second table and upped again. However, to my surprise, it 'replaces' the second table by removing the first table. Somehow pulumi did not detect the AWS error and thought the second DynamoDB table was created (with the same name).

Luckily, this was on my test environment...

### Example

Javascript snippet

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws-native";

const dynamodbTableHashKey = "PK";
const dynamodbTableRangeKey = "SK";
const dynamodbTableName1 = "table1";
const dynamodbTableName2 = "table1";

const table1 = new aws.dynamodb.Table(`dynamodb-1`, {
  attributeDefinitions: [
    {
      attributeName: dynamodbTableHashKey,
      attributeType: "S",
    },
    {
      attributeName: dynamodbTableRangeKey,
      attributeType: "S",
    },
  ],
  deletionProtectionEnabled: false,
  keySchema: [
    {
      attributeName: dynamodbTableHashKey,
      keyType: "HASH",
    },
    {
      attributeName: dynamodbTableRangeKey,
      keyType: "RANGE",
    },
  ],
  tableName: dynamodbTableName1,
  billingMode: "PAY_PER_REQUEST",
  timeToLiveSpecification: {
    attributeName: "TTL",
    enabled: false,
  },
}, { replaceOnChanges: ["tableName"], deleteBeforeReplace: true, });


// const table2 = new aws.dynamodb.Table("dynamodb-2", {
//   attributeDefinitions: [
//     {
//       attributeName: dynamodbTableHashKey,
//       attributeType: "S",
//     },
//     {
//       attributeName: dynamodbTableRangeKey,
//       attributeType: "S",
//     },
//   ],
//   deletionProtectionEnabled: false,
//   keySchema: [
//     {
//       attributeName: dynamodbTableHashKey,
//       keyType: "HASH",
//     },
//     {
//       attributeName: dynamodbTableRangeKey,
//       keyType: "RANGE",
//     },
//   ],
//   tableName: dynamodbTableName2,
//   billingMode: "PAY_PER_REQUEST",
//   timeToLiveSpecification: {
//     attributeName: "TTL",
//     enabled: false,
//   },
// }, { replaceOnChanges: ["tableName"], deleteBeforeReplace: true });
```

1. Up this snippet.
2. Remove comments at the end of the snippet, so a second table is created.
3. Get the error:

```
 aws-native:dynamodb:Table (dynamodb-2):
    error: 1 error occurred:
        * operation CREATE failed with "AlreadyExists": Resource of type 'AWS::DynamoDB::Table' with identifier 'table1' already exists.
```

4. Rename the table name within variable `dynamodbTableName2` to `table2`.
5. Run pulumi up, see that it will execute a replace statement where it deletes table1, which it should NOT do.

Clearly at step 3 pulumi should detect an error preventing the creation of the table.

### Output of `pulumi about`

```
NAME                VERSION
@pulumi/aws-native  0.92.0
@pulumi/pulumi      3.100.0
@pulumi/random      4.15.0
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by mikhailshilkov**
The PR does three things:

1. Cover client.Create with unit tests for all branches.
2. Refactor its code to be more concise and to return as quickly as possible. Return consistent error messages.
3. Add another special case to create logic to process AlreadyExists error.

Currently, if we receive an AlreadyExists error, we follow our default flow for all await errors: we proceed to reading the resource state, we see that it exists, and we return a partial error, which saves this resource in Pulumi state. This is wrong, because we should not pull an existing resource into state unexpectedly for a user (without an import). After the fix, we hard-fail on AlreadyExists.

Fix #1263
Fix #1138

### CODE REVIEW

**Review by danielrbradley — COMMENTED** [review]
Looks good on first glance but Let's stack this on https://github.com/pulumi/pulumi-aws-native/pull/1406 otherwise this is going to cause a lot more merging pain.

**Comment by mikhailshilkov** [comment]
> Let's stack this on https://github.com/pulumi/pulumi-aws-native/pull/1406 otherwise this is going to cause a lot more merging pain.

Why? I don't think #1406 changes the same files at all?

File: provider/pkg/client/client.go [hunk 1]
```diff
@@ -64,41 +64,34 @@ func (c *clientImpl) Create(ctx context.Context, typeName string, desiredState m
...
+			// to validate its existence. We should return immediately as a hard error.
+			return nil, nil, waitErr
 		}
-
-		// Resource was created but failed to fully initialize.
-		// If it has some state, return a partial error.
-		return &id, resourceState, waitErr
 	}
 	if pi.Identifier == nil {
 		return nil, nil, errors.New("received nil identifier while reading resource state")
```
Comment (mjeffryes) [inline provider/pkg/client/client.go:78]: nit. this error message doesn't quite make sense? We're not really in the middle of reading; we can't read b/c there was no id returned from the await

**Review by mjeffryes — APPROVED** [review]
Thanks for the thorough tests!
