### PR TITLE
SDK generation

### LINKED ISSUE #1640: Workflow failure: nightly-sdk-generation
## Workflow Failure

[nightly-sdk-generation](https://github.com/pulumi/pulumi-aws-native/blob/master/.github/workflows/nightly-sdk-generation.yml) has failed. See the list of failures below:

- [2024-07-19T04:55:03.000Z](https://github.com/pulumi/pulumi-aws-native/actions/runs/10002663014)

- [2024-07-22T04:40:10.000Z](https://github.com/pulumi/pulumi-aws-native/actions/runs/10034746219)

- [2024-07-23T04:39:55.000Z](https://github.com/pulumi/pulumi-aws-native/actions/runs/10052804766)

### PR DESCRIPTION
**Pull request by corymhall**
Had to run the nightly schema generation manually because it was failing
on enums ending in `*Input` & `*Output`. I added a special case for the
couple new ones that came in.

If anyone has any suggestions on a generic solution we could use (e.g.
`Inputx`) I'm open to it.

closes #1640

### CODE REVIEW

File: provider/pkg/schema/gen.go [hunk 1]
```diff
@@ -1428,6 +1428,11 @@ func (ctx *cfSchemaContext) genEnumType(enumName string, propSchema *jsschema.Sc
 		if values.Has(str) {
 			continue
 		}
+
+		// Enum values cannot end in `*Input` or `*Output`. Special casing these two instances
+		if (typName == "FlowNodeType" || typName == "FlowVersionFlowNodeType") && (str == "Input" || str == "Output") {
```
Comment (t0yv0) [inline provider/pkg/schema/gen.go:1433]: This change right?

**Review by t0yv0 — APPROVED** [review]
This looks good. I'd not generalize until it strikes again.

In the future if you could separate the substantive commits from "regenerate the code" commits that'd help a little bit finding the changes when reviewing. Thank you!
